var events=[];
events.push({name:"Yuramon talk about Invisible Bridge",triggers:"being able to pass invisible bridge.;Yuramon talks about Ogremon."})

var digimon=[];
//== Native Forest ==
digimon.push({region:"Native Forest",name:"Agumon",fight:"1",trigger:"None",level:"Rookie",prosperityPoints:"1",location:"Screen south of Green Gym",requirement:"He will challenge you to a fight - win it.",unlocks:"Item Bank"});
digimon.push({region:"Native Forest",name:"Kunemon",fight:"1",trigger:"Have Food",level:"Rookie",prosperityPoints:"1",location:"left screen from the Forest toilet",requirement:"He will ask you for food, once you give him something he will fight you - win the fight.",unlocks:"direct path from File City to Digimon bridge"});
digimon.push({region:"Native Forest",name:"Palmon",fight:"1",trigger:"None",level:"Rookie",prosperityPoints:"1",location:"south screen from Forest toilet",requirement:"Talk to him 3 times and he will fight you - win the fight.",unlocks:"upgrades meat farm to yield giant meat, sells you giant meat for 500 bits each"});
digimon.push({region:"Native Forest",name:"Coelamon",fight:"0",trigger:"16:00-19:59",level:"Champion",prosperityPoints:"2",location:"southeast from Kunemon's bed",requirement:"Go to his screen at dusk (16:00-19:59) and he will swim there. Talk to him, he will bring you to the jungle. Go north and over the now repaired Digimon bridge and go back where you found Coelamon the first time.<br />Talk to him again and he'll join the town.",unlocks:"Shop"});
digimon.push({region:"Native Forest",name:"Seadramon",fight:"0",trigger:"08:00-08:59/17:00-17:59 & have fishing rod",level:"Champion",prosperityPoints:"2",location:"Dragon Lake Island",requirement:"Go to the spot between 08:00 and 08:59 or between 17:00 and 17:59 and try to fish the big, fast moving fish.<br />It might take some time until he takes the bait. Once he nibbles you have to get the timing right, as a rule of thump you should let the swimmer bob 3 times before pressing X.<br />Once you got he hooked you have to be patient - hold the tension bar in the middle and you'll eventually catch it. Chose the Friend option to recruit it.",unlocks:"He gives you a flute you can use at the coast of Dragon Lake by pressing X to get you to Beetle Island",comment:"Choosing 'Item' gives you am Evolution Item to Seadramon, 'Technique' teaches you an Ice/Water Attack (Aqua Magic, Winter Blast and Giga Freeze, in this order)"});
digimon.push({region:"Native Forest",name:"Etemon",fight:"1",trigger:"50pp",prosperityTrigger:"50",level:"Ultra",prosperityPoints:"3",location:"South from Kunemon's Bed when having 50+ Prosperity. His appearance is triggered by interacting with the door and does 30% damage of the max HP of your Digimon.",requirement:"Win the fight against him.",unlocks:"Sells the Etemon evolution item at Digibridge"});
digimon.push({region:"Native Forest",name:"Ninjamon",fight:"1",trigger:"Secret Shop",recruitTrigger:"Numemon/Mojyamon/Devimon/Mamemon",level:"Champion",prosperityPoints:"2",location:"Digimon Bridge, when walking to Kunemon's bed with one Digimon that works in the secret shop recruited. The big shop building is not required.",requirement:"win the fight against him",unlocks:"Gives you information about Items when you talk to him"});
//== Beetle Island ==
digimon.push({region:"Beetle Island",name:"Kuwagamon",fight:"0",trigger:"Seadramon",recruitTrigger:"Seadramon",level:"Champion",prosperityPoints:"2",location:"Bettle Island, left training hall",requirement:"Talk to him and chose the 2nd option",unlocks:"improves training of HP, Offense and Brains in Green Gym"});
digimon.push({region:"Beetle Island",name:"Kabuterimon",fight:"0",trigger:"Seadramon & Greymon",recruitTrigger:"Seadramon,Greymon",level:"Champion",prosperityPoints:"2",location:"Bettle Island, right training hall once you've recruited Greymon",requirement:"Talk to him and chose the 2nd option",unlocks:"improves training of MP, Defense and Speed in Green Gym"});
//== File City ==
digimon.push({region:"File City",name:"Greymon",fight:"1",trigger:"15pp & leave Jijimon's hut",prosperityTrigger:"15",level:"Champion",prosperityPoints:"2",location:"When you talk to Jijimon and leave his house with a prosperity rate of 15 or higher.",requirement:"win the fight against him",unlocks:"Arena"});
digimon.push({region:"File City",name:"Airdramon",fight:"1",trigger:"50pp & leave Jijimon's hut",prosperityTrigger:"50",level:"Champion",prosperityPoints:"2",location:"When you talk to Jijimon and leave his house with a prosperity rate of 50 or higher. He'll deal 10% damage of your max HP before the fight starts.",requirement:"win the fight against him and he'll join the town after you beat Machinedramon.",unlocks:"Fortune teller in arena"});
//== Random encounters ==
//These encounters have a random 3% chance of spawning every time you enter their screen.
digimon.push({region:"Tropical Jungle",name:"Piximon",fight:"1",trigger:"3% chance",level:"Ultra",prosperityPoints:"3",location:"2nd jungle screen when coming from the Digibridge",requirement:"win the fight against him",unlocks:"sells the 'Training Manual' for 50'000 bits in the Item Shop, he has a 20% of spawning there each time you enter it."});
digimon.push({region:"Mt. Panorama",name:"Mamemon",fight:"1",trigger:"3% chance",level:"Ultra",prosperityPoints:"3",location:"Top of Mt. Panorama",requirement:"win the fight against him",unlocks:"Secret Shop (sells stat Disks)"});
digimon.push({region:"Factorial Town",name:"MetalMamemon",fight:"1",trigger:"3% chance",recruitTrigger:"Whamon",level:"Ultra",prosperityPoints:"3",location:"2nd screen of factorial town when entering via Whamon",requirement:"win the fight against him",unlocks:"Curling enemy (special prices: Giromon, Mamemon, MetalMamemon and Piximon evolution items)"});
//== Drill Tunnel ==
digimon.push({region:"Drill Tunnel",name:"Drimogemon",fight:"1",trigger:"Meramon & talk & wait 3 days",recruitTrigger:"Meramon",level:"Champion",prosperityPoints:"2",requirement:"First fight the Drimogemon in the kitchen (left screen from 'hub' screen), this unlocks the Drimogemon on the right screen to drill the tunnel.<br />Once you talked to him it takes 5 ingame days for him to dig the tunnel - the time can be shortened by carrying dirt for him.<br />When he is finished you have to move a rock for him that unlocks Meramon's cave - you need a champion for that. After you've recruited Meramon he will appear in the lower part of the cave.<br />Talking to him triggers another 3 ingame days event to open a path to Gear Savanna. Once he finished that he'll join the town once you talk to him again.",unlocks:"Treasure Hunter shop - (also: Meramon's Cave, Path through Drill Tunnel to Gear Savanna)"});
digimon.push({region:"Drill Tunnel",name:"Meramon",fight:"1",trigger:"Fight Drimogemon & carry dirt 10 times/wait 5 days",level:"Champion",prosperityPoints:"2",location:"Meramon's cave, which has to be opened by Drimogemon first",requirement:"win the fight against him",unlocks:"Restaurant, Path to Gear Savanna over Mt. Panorama"});
//== Gear Savanna ==
digimon.push({region:"Gear Savanna",name:"Elecmon",fight:"0",trigger:"None",level:"Rookie",prosperityPoints:"1",location:"Top left screen of Gear Savanna at the entrance to Factorial Town",requirement:"Talk 3 times to him, you'll get 20% of your max HP as damage every time you talk to him",unlocks:"Electricity in the town, adding lights that turn on at night time"});
digimon.push({region:"Gear Savanna",name:"Patamon",fight:"3",trigger:"None",level:"Rookie",prosperityPoints:"1",location:"Center top screen of the area",requirement:"Win 3 times in a row against him",unlocks:"Shop"});
digimon.push({region:"Gear Savanna",name:"Biyomon",fight:"0",trigger:"None",level:"Rookie",prosperityPoints:"1",location:"the screen south from Patamon",requirement:"Talk to Biyomon, she will run away, talk to her again and look for a spot that opens a chat menu (it's close to the point where Biyomon stood) and pick 'Wait', telling your Digimon to hunt Biyomon.<br />This one is heavy RNG, so continue to do that until you succeed.",unlocks:"Shop"});
digimon.push({region:"Gear Savanna",name:"Sukamon",fight:"0",trigger:"None",level:"Champion",prosperityPoints:"1",location:"Mt. Trash",requirement:"Talk to the Sukamon above the MP training. You won't get a join message, but you'll see him near the toilet sometimes.",unlocks:"Nothing"});
digimon.push({region:"Gear Savanna",name:"Leomon",fight:"0",trigger:"45pp & Meramon",prosperityTrigger:"45",recruitTrigger:"Meramon",level:"Champion",prosperityPoints:"2",location:"South from Mt. Trash you'll find a Patamon chased by a Goburimon that gets rescued by Leomon. The screen left to that you can find Leomon.<br />Once you have the table and talk to Leomon for him to join the town.",requirement:"You have to get the stone table from Leomon's Cave inside the Drill Tunnel (south from the hub). The cave gets opened once you have 45 prosperity and Meramon in the town.",unlocks:"Nothing"});
//== Tropical Jungle and sub Regions ==
digimon.push({region:"Tropical Jungle",name:"Vegiemon",fight:"0",trigger:"Wait until the 15th of the month",level:"Champion",prosperityPoints:"2",location:"exit the toilet screen to the right",requirement:"On day 15 of every year you can collect a Rain Plant near the meat field. Talk to Tanemon afterwards. Once you did that you'll find a small plant in the target screen.<br />Interact with the plant and use the Rain Plant. Vegiemon will appear and ask a question, he'll join the town regardless of your answer.",unlocks:"upgrades meat farm to yield sirloin, sells you Supercarrot and Hawk Raddish"});
digimon.push({region:"Tropical Jungle",name:"Centarumon",fight:"0",trigger:"None",level:"Champion",prosperityPoints:"2",location:"If you keep going right from the DigiBridge you'll end up in Amida Forest (Right -> Right -> Up)",requirement:"You have to find the exist to the maze. It's an Amida kuji, so you have to switch the lane whenever possible.<br />The exit is random, so you might fail getting the right exit a few times. Walking into the wrong door ends up with you being teleported back to the start.<br />If you don't switch the lane or try to go back Centarumon will shoot you, dealing 50% of your max HP as damage. If your HP reach 1, you'll get teleported back and you have to heal in order to continue.<br />Once you made it to the right exit Centarumon will join the city and open a path to the Ancient Dino Region.",unlocks:"A Clinic where you can heal and rest your Digimon and buy bandages as well as medicine.",comment:"You can find many valuable Items in the maze, so failing it a few times can actually be helpful.<br />Watch out when entering the Ancient Dino Region as you almost immediately encounter Tyrannmon, who is quite strong for the early game."});
digimon.push({region:"Tropical Jungle",name:"Tyrannomon",fight:"1",trigger:"Centarumon",recruitTrigger:"Centarumon",level:"Champion",prosperityPoints:"2",location:"Ancient Dino Region",requirement:"He'll attack you once you walk a few steps into the Ancient Dino Region, win the fight.<br />This allows you to visit the whole region until you meet him in front of the Speedy Time Zone. Talk to him and he lets you enter it. At the bone tunnel, there is a hidden passage in the top left.<br />There you'll find Meteormon. Beat him in a fight and you can recruit Tyrannomon afterwards.",unlocks:"Restaurant"});
digimon.push({region:"Tropical Jungle",name:"Betamon",fight:"0",trigger:"None",level:"Rookie",prosperityPoints:"1",location:"Head to the right of the screen where Coelamon brings you but exit the screen on the top.",requirement:"Talk to him and he'll join the town.",unlocks:"Shop"});
digimon.push({region:"Tropical Jungle",name:"Bakemon",fight:"0",trigger:"None",level:"Champion",prosperityPoints:"2",location:"Head straight north from the point where Coelamon brought you until you enter the Overdell Cemetery",requirement:"Talk to Bakemon and answer Yes, Yes, No and he'll join the town.",unlocks:"Nothing",comment:"Having Bakemon yourself won't allow you to understand what he says. It will, however, alter the dialogue when talking to Bakemon in the Town."});
//== Mt. Panorama ==
digimon.push({region:"Mt. Panorama",name:"Unimon",fight:"0",trigger:"Recruit Centarumon and talk to him once. Beat Meramon or walk all the way around the island",recruitTrigger:"Centarumon",level:"Champion",prosperityPoints:"2",location:"Second screen when you enter Mt. Panorama via Native Forest after you recruited Centarumon and talked to him once.",requirement:"Give him an healing Item (e.g. sm. recovery Floppy) and he'll join the town",unlocks:"Shop"});
digimon.push({region:"Mt. Panorama",name:"Vademon",fight:"0",trigger:"45pp & Shellmon",prosperityTrigger:"45",recruitTrigger:"Shellmon",level:"Ultra",prosperityPoints:"3",location:"Chose the right exit from Unimon",requirement:"1. Go to his location, step on the marks on the floor, a textbox should appear.<br />2. Read Shellmon's bulletin board (Entry 2), go back to the location and step on the marks on the floor, a textbox should appear.<br />3. With 45pp+, read Shellmon's bulletin board (Entry 8), go back to the location and stop on the marks on the floor - Vademon should appear and join the town.",unlocks:"Restaurant"});
//== Misty Trees ==
//In order to be able to navigate properly through Misty Trees you need to have talked to ShogunGekomon. For that you have to find and fight Otamamon at the 2nd Geko swamp screen.
//Beware, Otamamon has a 33% chance of spawning. To find Cherrymon go to the right and then to the top.
digimon.push({region:"Misty Trees",name:"Gabumon",fight:"1",trigger:"None",level:"Rookie",prosperityPoints:"1",location:"When you enter Misty Trees from Geko Swamp, exit the screen on the left. Gabumon is hiding behind a tree.",requirement:"win the fight against him",unlocks:"Improves Treasure Hunter shop, increases chance to get a valuable item (evolution item/chip)."});
digimon.push({region:"Misty Trees",name:"Kokatorimon",fight:"1",trigger:"4:00-6:59",level:"Champion",prosperityPoints:"2",location:"When you enter Misty Trees from Geko Swamp, exit the screen 2 times on the right. Kokatorimon will be there in the early morning between 4:00 and 6:59.",requirement:"win the fight against him",unlocks:"A statue near the toilet"});
//== Toy Town ==
digimon.push({region:"Toy Town",name:"Monzaemon",fight:"1",trigger:"Raise a Numemon",level:"Ultra",prosperityPoints:"3",location:"Monzaemon Costume House",requirement:"You need a Monzaemon as your partner Digimon. You can easily get one by using the Monzaemon costume in the left house of Toy Town while having a Numemon.<br />Talk to the Tinmon in the right house, once you finished go to the big villa in the middle and you should be able to open the door. Follow the path until you find 2 boxes.<br />You'll have to fight WaruMonzaemon there, who gives you a Gear Item. Bring this item back to the Tinmon in the right house and you're done.",unlocks:"Monzaemon costume in the back of Jijimon's house. Doesn't have any use."});
//== Factorial Town ==
digimon.push({region:"Factorial Town",name:"Andromon",fight:"0",trigger:"Giromon & Numemon",recruitTrigger:"Giromon,Numemon",level:"Ultra",prosperityPoints:"3",location:"In the middle of factorial town, there is a small house where Andromon is in.",requirement:"Talk to him once you've beating Giromon, that will allow you to recruit Numemon. Talk to him again after you've recruited Numemon.<br />Now, once you have the large shop, restaurant, hospital and gym and visited the screen once you should be able to recruit by talking twice to him again.",unlocks:"Nothing"});
digimon.push({region:"Factorial Town",name:"Giromon",fight:"1",trigger:"12:00-12:01/24:00-00:01",recruitTrigger:"Whamon",level:"Ultra",prosperityPoints:"3",location:"When leaving the screen with Andromon's house on the right side at 12 a.m. / p.m. you can enter the factory. Enter the left door on the 2nd screen.",requirement:"win the fight against him. You can recruit him by talking to him again once you have recruited Andromon.",unlocks:"Giromon's Jukebox in the restaurant. WARNING, in NTSC versions the Jukebox is bugged and causes your game to crash!"});
digimon.push({region:"Factorial Town",name:"Numemon",fight:"1",trigger:"Giromon",recruitTrigger:"Giromon",level:"Champion",prosperityPoints:"1",location:"North the central screen there is a ladder that leads to the sewers.",requirement:"After you've beaten Giromon and talked to Andromon the fog in the sewers should be gone. Talk to Numemon and win the fight against him.",unlocks:"Secret shop (sells Enemy Bell and Enemy Repel)"});
//== Grey Lord's Mansion ==
//You need a Virus type Digimon to enter the Mansion."});
digimon.push({region:"Grey Lord's Mansion",name:"SkullGreymon",fight:"1",trigger:"35pp & Shellmon",prosperityTrigger:"35",recruitTrigger:"Shellmon",level:"Ultra",prosperityPoints:"3",requirement:"Enter the Mansion, use the door on the right side of the stairs, keep going left until you reach a large room with a fireplace - talk to the fireplace and you'll find the mansion key.<br />Head back to the room under the stairs but this time enter the upper door. Behind the 2 Rockmon is a spot where you'll fall though (you get 30% of your max HP damage).<br />Use the upper door and talk to the coffin, which opens up the hidden Room where Myotismon is. Talk to him and he'll give you the fridge key and a quest to bring him meat.<br />Go back to the screen where the 3 Soulmon are and talk to the fridge. After that leave the Mansion and you'll find the 'Steak' in front of it. Bring it to Myotismon and you're done for now.<br />Once you have 35 prosperity points read the message about Myotismon at Shellmon's bulletin board and head back to the mansion.<br />Visit the hidden room and the dining room each in which a dialogue will trigger. Then head to the exit of the mansion again and a cutscene with Devimon will be triggered.<br />After the cutscene you can enter the lower right door which was previously locked, where you'll find the secret lab with SkullGreymon. Defeat him.<br />Once you've defeated SkullGreymon you can talk to Myotismon in the room before and finish the recruitment. Talk to him twice!",unlocks:"Fights in Arena"});
//== Great Canyon ==
//You need to talk with Yuramon in File City after you unlocked the Digibridge and he'll tell you something about an invisible bridge, after that you can head to the Great Canyon entrance and use the invisible bridge."});
digimon.push({region:"Great Canyon",name:"Monochromon",fight:"0",trigger:"None",level:"Champion",prosperityPoints:"2",location:"The Shop next to the Toilet in the first screen.",requirement:"When talking to him he'll let you work in his Shop to test if you're 'worthy'. If you manage to have over 3072 Bits profit he'll join the town.<br />The Shop Minigame is very RNG intensive and hard. Goburimon and Mucho are usually easy customers (you can often sell them expensive stuff, even if they're unhappy)<br />while Gotsumon and Weedmon have to treated carefully. This minigame costs you 8h of time and gives you a bit of money.",unlocks:"Shop"});
digimon.push({region:"Great Canyon",name:"Birdramon",fight:"1",trigger:"None",level:"Champion",prosperityPoints:"2",location:"When you chose the right path you'll eventually come to an elevator. Chose UP and you'll end up a Birdramon's nest.",requirement:"Walk into the nest and Birdramon will appear. Win the fight and she will join your town.",unlocks:"Birdra Transport, the quick travel System of this game",comment:"Once you've beaten Birdramon she'll take you back to File City"});
digimon.push({region:"Great Canyon",name:"Shellmon",fight:"0",trigger:"Ogremon 1",level:"Champion",prosperityPoints:"2",location:"Great Canyon Bridge",requirement:"After you've beaten Ogremon in his Fortress, use the elevator from the last room and follow the path until you hear someone calling for help.<br />Head back to Ogre Fortress and go to the elevator that can lead you to Birdramon's nest - press one times UP. Leave the Canyon in direction Freezeland and in the first Freezeland screen<br />you'll find another bridge to the Canyon. Use it and you'll find Shellmon who will join your town once you talk to him.",unlocks:"Shellmon's Bulleting Board. Contains some information as well as hints and trigger for certain recruitments."});
//== Freezeland ==
digimon.push({region:"Freezeland",name:"Penguinmon",fight:"0",trigger:"None",level:"Rookie",prosperityPoints:"1",location:"Head to the screen with the guidepost and follow the right way and leave the first screen as far north as you can on the right side.",requirement:"Talk with Penguinmon and he'll challenge you to a match of Curling. Win the game and he'll join the city. If you lose you can play again, but you have to bring him any fish.<br />The AI is at sometimes a bit stupid.",unlocks:"Curling in the Arena of your town."});
digimon.push({region:"Freezeland",name:"Mojyamon",fight:"0",trigger:"None",level:"Champion",prosperityPoints:"2",location:"There are 3 Mojyamon, all can be reached from the same screen where you can enter Penguinmon's screen. (Lower right side and south side)",requirement:"Each Mojyamon offers 3 trades and the last Mojyamon you traded with will join your town once you've traded all trades at least once.<br />You'll need the following Items: Digimushroom, Supercarrot, Happymushroom, Giant Meat, Black Trout, Hispeed Disk, Omnipotent, med. recovery and Digianchovy.",unlocks:"Secret shop - sells Rest pillow (more sleep regen) and health shoes (HP+MP regen while walking)",comment:"If you recruited Vegimon already and don't have any Giant Meat left you can buy it from the Secret Shop in Gear Savanna."});
digimon.push({region:"Freezeland",name:"Whamon",fight:"0",trigger:"Ogremon 2",level:"Champion",prosperityPoints:"2",requirement:"After you've beaten Ogremon in Ogre Fortress, leave the screen that leads to Penguinmon and Mojyamon on the left and head straight down the ice pier.<br />You'll find Whamon there who will take you to a secret cave that contains the 3rd phase of the Ogremon recruitment, after which Whamon will join.",unlocks:"Fast travel to Factorial Town and the secret cave (you can find an evolution item for Digitamamon there)"});
digimon.push({region:"Freezeland",name:"Angemon",fight:"0",trigger:"None",level:"Champion",prosperityPoints:"2",requirement:"Enter the Ice Sanctuary and talk to statue. After that go in the direction of the exit and your Digimon will open the hidden passge.<br />Once your down the stairs, stay on the right wall and you'll find a secret entrance in the first small room.",comment:"You are supposed to enter Ice Sanctuary only with Vaccine Digimon, but there are glitches that allow entrance with any Digimon. ( https://www.youtube.com/watch?v=Bbib9_be-EM )",unlocks:"He'll give you hints about the Digimon you haven't recruited yet."});
digimon.push({region:"Freezeland",name:"Frigimon",fight:"0",trigger:"Sick Digimon weak against cold",level:"Champion",prosperityPoints:"2",requirement:"Take a Digimon that doesn't like cold and make it sick. Easiest way to get sick is using Moldy Meat (can be bought at the vending machine in Ancient Dino Region).<br />Once sick you have to go to a certain spot to trigger the event. So just walk around a bit in Freezeland till your Digimon 'passes out'.<br />After that get another Digimon, that doesn't not like the cold and talk to Frigimon again, making him joining the city.",unlocks:"Restaurant",comment:"Suitable Digimon are any Fresh and In-Training Digimon, Agumon, Greymon, Tyrannomon, Meramon, Monochromon, Kunemon, Kuwagamon, Kabuterimon and Birdramon"});
digimon.push({region:"Freezeland",name:"Garurumon",fight:"2",trigger:"None",level:"Champion",prosperityPoints:"2",location:"South from Frigimon's house",requirement:"Fight him and win the fight. He'll challenge you again for 4 p.m. the next day. If you miss that time you can still fight him, but he'll have more HP then.<br />The 2nd fight has to be done without items or command, so having a strong Digimon is recommended!",unlocks:"Restaurant"});
//== Moving Recruitments ==
digimon.push({region:"Various",name:"Nanimon",fight:"0",trigger:"Tyrannomon & Ogremon 2 & Leomon & Andromon & Monzaemon",recruitTrigger:"Tyrannomon,Leomon,Andromon,Monzaemon",level:"Champion",prosperityPoints:"1",requirement:"Nanimon appears at 5 locations after certain recruitments are done. There is no set order you have to visit these places.<br />1. Ogre Fortress, last room - after Phase 3 of Ogremon recruitment<br />2. Toy Town, last room - after Monzaemon recruitment<br />3. Speedy Dino Region, where Meteormon was - after Tyrannomon recruitment<br />4. Leomon's Cave - after Leomon recruitment<br />5. Factorial Town Sewers - after Andromon recruitment",unlocks:"The first time you find him he'll drop a keychain that increases you Inventory to 20 slots, the last time you find him he'll drop a Key Chain, increasing your Inventory to 30 slots.",comment:"You can see him in the Item Bank, but there is no way to interact with him."});
digimon.push({region:"Various",name:"Ogremon",fight:"4",trigger:"Talk to Yuramon",level:"Champion",prosperityPoints:"2",requirement:"1. Once you've visited the Great Canyon (you need to trigger the textbox at the invisible bridge) talk to Yuramon and he'll tell something about bandits. Head back to the canyon and on the screen before the elevator chose the right path.<br />You'll encounter and fight Ogremon and 2 Agumon there.<br />2. Go to the elevator and chose DOWN and exit the screen on the bottom. You'll find Ogre Fortress there - enter it and in the last room you'll fight again against Ogremon and 2 Agumon.<br />(You can now recruit Shellmon)<br />3. Go to Freezeland and find Whamon. The Whamon recruitment is the whole phase. You'll fight against Ogremon, WaruSeadramon and Gabumon.<br />4. Go to the Drill Tunnel and in the hub you'll fight again against Ogremon and 2 Agumon. After that Ogremon will join the town.",unlocks:"Nothing"});
//== Mt. Infinity ==
digimon.push({region:"Mt. Infinity",name:"Devimon",fight:"1",trigger:"50pp",prosperityTrigger:"50",level:"Champion",prosperityPoints:"2",location:"6th level of Mt. Infinity",requirement:"win the fight against him",unlocks:"Secret shop - sells DV chips (massive stats gain, reduce lifetime by 24h)"});
digimon.push({region:"Mt. Infinity",name:"Megadramon",fight:"1",trigger:"50pp",prosperityTrigger:"50",level:"Ultra",prosperityPoints:"3",location:"10th level of Mt. Infinity",requirement:"win the fight against him",unlocks:"?"});
digimon.push({region:"Mt. Infinity",name:"MetalGreymon",fight:"1",trigger:"50pp",prosperityTrigger:"50",level:"Ultra",prosperityPoints:"3",location:"11th level of Mt. Infinity",requirement:"win the fight against him",unlocks:"Gives your Digimon nicknames."});
digimon.push({region:"Mt. Infinity",name:"Digitamamon",fight:"1",trigger:"50pp & beaten Machinedramon",prosperityTrigger:"50",level:"Ultra",prosperityPoints:"3",location:"12th level of Mt. Infinity after you've beaten Machinedramon",requirement:"win the fight against him",unlocks:"Restaurant - allows Digitamamon glitch (eating food without hunger, allowing statsgain in no time)"});

var obj;
for(var i=0;i<digimon.length;i++){
    digimon[i].recruited=false;
    /*obj = digiStatsStory.filter(function(obj) {
        return obj.Digimon === digimon[i].name;
    })[0];
    console.log(i+":"+obj);*/
    digimon[i].data=searchByName(digiEnemies,digimon[i].name);
}














